spring:
  datasource:
    url: jdbc:mysql://localhost:3307/osahaneat
    username: root
    password: admin123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
